<span style="font-size:45px;">1 - Create a series</span>

In [97]:
import pandas as pd

In [98]:
ages = pd.Series([22, 25, 31, 28], index=["Ahmed", "Mona", "Youssef", "Salma"])

In [99]:
ages

Ahmed      22
Mona       25
Youssef    31
Salma      28
dtype: int64

In [100]:
ages.shape

(4,)

In [101]:
ages.dtypes

dtype('int64')

In [102]:
ages.value_counts()

22    1
25    1
31    1
28    1
Name: count, dtype: int64

In [103]:
dictA={"Name":["Ali", "Ahmed", "Sara", "Fatima", "Hassan", "Amera"],
       "Department":["IT", "HR", "IT", "Sales", "IT", "Sales"],
       "Age":[20, 30, 40, 39, 42, 35], 
       "Salary":[1000, 2000, 3000, 4000, 5000, 6000],
       "City" : ["Cairo", "Alexndria", "Matrouh", "Suez", "Banha", "Giza"]}

df=pd.DataFrame(dictA, index=['A', 'B', 'C', 'D', 'E', 'F'])

In [104]:
df.head()

     Name Department  Age  Salary       City
A     Ali         IT   20    1000      Cairo
B   Ahmed         HR   30    2000  Alexndria
C    Sara         IT   40    3000    Matrouh
D  Fatima      Sales   39    4000       Suez
E  Hassan         IT   42    5000      Banha

In [105]:
df.tail()

     Name Department  Age  Salary       City
B   Ahmed         HR   30    2000  Alexndria
C    Sara         IT   40    3000    Matrouh
D  Fatima      Sales   39    4000       Suez
E  Hassan         IT   42    5000      Banha
F   Amera      Sales   35    6000       Giza

In [106]:
df.shape

(6, 5)

In [107]:
df.columns

Index(['Name', 'Department', 'Age', 'Salary', 'City'], dtype='str')

In [108]:
df.dtypes

Name            str
Department      str
Age           int64
Salary        int64
City            str
dtype: object

<span style="font-size:45px;">2. Inspecting the DataFrame</span>

In [109]:
df.head(3)

    Name Department  Age  Salary       City
A    Ali         IT   20    1000      Cairo
B  Ahmed         HR   30    2000  Alexndria
C   Sara         IT   40    3000    Matrouh

In [110]:
df.tail(2)

     Name Department  Age  Salary   City
E  Hassan         IT   42    5000  Banha
F   Amera      Sales   35    6000   Giza

In [111]:
df.info(
)

<class 'pandas.DataFrame'>
Index: 6 entries, A to F
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Department  6 non-null      str
 2   Age         6 non-null      int64
 3   Salary      6 non-null      int64
 4   City        6 non-null      str
dtypes: int64(2), str(3)
memory usage: 288.0+ bytes

In [112]:
df.describe()
# The function ignores "Name" and "Department" columns because they are not numeric

             Age       Salary
count   6.000000     6.000000
mean   34.333333  3500.000000
std     8.213810  1870.828693
min    20.000000  1000.000000
25%    31.250000  2250.000000
50%    37.000000  3500.000000
75%    39.750000  4750.000000
max    42.000000  6000.000000

In [113]:
df.describe(include=("all"))

       Name Department        Age       Salary   City
count     6          6   6.000000     6.000000      6
unique    6          3        NaN          NaN      6
top     Ali         IT        NaN          NaN  Cairo
freq      1          3        NaN          NaN      1
mean    NaN        NaN  34.333333  3500.000000    NaN
std     NaN        NaN   8.213810  1870.828693    NaN
min     NaN        NaN  20.000000  1000.000000    NaN
25%     NaN        NaN  31.250000  2250.000000    NaN
50%     NaN        NaN  37.000000  3500.000000    NaN
75%     NaN        NaN  39.750000  4750.000000    NaN
max     NaN        NaN  42.000000  6000.000000    NaN

<span style="font-size:45px;">3 - Selecting</span>

In [114]:
df['Name'].dtypes

In [115]:
df[['Name']]
# The difference between a single "[]" and double "[[]]" is that the double "[[]]" will return a Series object, while the single "[]" will return a DataFrame object.

     Name
A     Ali
B   Ahmed
C    Sara
D  Fatima
E  Hassan
F   Amera

In [116]:
slice= df.loc["A":"B", ["Name", "Salary"]]
slice

    Name  Salary
A    Ali    1000
B  Ahmed    2000

In [117]:
slice = df.iloc[0:2, [0, 3]]
slice
# The reaosn loc returns [0:2] returns three rows and iloc returns tow rows is because iloc is zero based and loc is one based

    Name  Salary
A    Ali    1000
B  Ahmed    2000

<span style="font-size:45px;">4 - Filtering</span>

In [118]:
df[df["Age"] > 30]

     Name Department  Age  Salary     City
C    Sara         IT   40    3000  Matrouh
D  Fatima      Sales   39    4000     Suez
E  Hassan         IT   42    5000    Banha
F   Amera      Sales   35    6000     Giza

In [119]:
df[df["Department"]=="IT"]

     Name Department  Age  Salary     City
A     Ali         IT   20    1000    Cairo
C    Sara         IT   40    3000  Matrouh
E  Hassan         IT   42    5000    Banha

In [120]:
df[df["Salary"]> 3000]

     Name Department  Age  Salary   City
D  Fatima      Sales   39    4000   Suez
E  Hassan         IT   42    5000  Banha
F   Amera      Sales   35    6000   Giza

<span style="font-size:45px;">5 - Modifying Data</span>

In [121]:
def inc10(x):
    return x*1.10

def inc1(x):
    return x+1

In [122]:
df["Salary_Bonus"]=df["Salary"].apply(inc10)
df["Age"]=df["Age"].apply(inc10)
df = df.rename(columns={'Salary': 'Monthly_Salary'})

In [124]:
df

     Name Department   Age  Monthly_Salary       City  Salary_Bonus
A     Ali         IT  22.0            1000      Cairo        1100.0
B   Ahmed         HR  33.0            2000  Alexndria        2200.0
C    Sara         IT  44.0            3000    Matrouh        3300.0
D  Fatima      Sales  42.9            4000       Suez        4400.0
E  Hassan         IT  46.2            5000      Banha        5500.0
F   Amera      Sales  38.5            6000       Giza        6600.0

In [125]:
df.drop("City", axis=1)

     Name Department   Age  Monthly_Salary  Salary_Bonus
A     Ali         IT  22.0            1000        1100.0
B   Ahmed         HR  33.0            2000        2200.0
C    Sara         IT  44.0            3000        3300.0
D  Fatima      Sales  42.9            4000        4400.0
E  Hassan         IT  46.2            5000        5500.0
F   Amera      Sales  38.5            6000        6600.0

<span style="font-size:45px;">6 - Missing Data</span>

In [127]:
import numpy as np

In [130]:
df.loc[1, "Age"] = np.nan
df.loc[4, "City"] = None

In [ ]:
df["Age"].dtype
# pandas automatically upcasts the entire column's data type from int64 to float64 so it can seamlessly accommodate the floating-point NaN value.

dtype('float64')

In [133]:
print(df.isnull().sum())

Name              2
Department        2
Age               2
Monthly_Salary    2
City              2
Salary_Bonus      2
dtype: int64

In [134]:

df["Age"] = df["Age"].fillna(df["Age"].mean())
df["City"] = df["City"].fillna("Unknown")

In [135]:
df

     Name Department        Age  Monthly_Salary       City  Salary_Bonus
A     Ali         IT  22.000000          1000.0      Cairo        1100.0
B   Ahmed         HR  33.000000          2000.0  Alexndria        2200.0
C    Sara         IT  44.000000          3000.0    Matrouh        3300.0
D  Fatima      Sales  42.900000          4000.0       Suez        4400.0
E  Hassan         IT  46.200000          5000.0      Banha        5500.0
F   Amera      Sales  38.500000          6000.0       Giza        6600.0
1     NaN        NaN  37.766667             NaN    Unknown           NaN
4     NaN        NaN  37.766667             NaN    Unknown           NaN

In [137]:
df.loc[1, "Age"] = np.nan
df.loc[4, "City"] = None

len_before = len(df)
print(f"Length before dropna: {len_before}")  # Output: 5

df_dropped = df.dropna()
len_after = len(df_dropped)
print(f"Length after dropna: {len_after}")  # Output: 3

Length before dropna: 8
Length after dropna: 6

In [138]:
avg_salary = df.groupby("Department")["Monthly_Salary"].mean()
print(avg_salary)

Department
HR       2000.0
IT       3000.0
Sales    5000.0
Name: Monthly_Salary, dtype: float64

In [139]:
summary_stats = df.groupby("Department")["Monthly_Salary"].agg(
    ["mean", "max", "count"]
)
print(summary_stats)

              mean     max  count
Department
HR          2000.0  2000.0      1
IT          3000.0  5000.0      3
Sales       5000.0  6000.0      2

In [140]:
dept_counts = df["Department"].value_counts()
print(dept_counts)

Department
IT       3
Sales    2
HR       1
Name: count, dtype: int64

In [141]:
df["Level"] = df["Monthly_Salary"].apply(
    lambda x: "High" if x >= 15000 else "Low"
)
print(df)

     Name Department        Age  Monthly_Salary       City  Salary_Bonus Level
A     Ali         IT  22.000000          1000.0      Cairo        1100.0   Low
B   Ahmed         HR  33.000000          2000.0  Alexndria        2200.0   Low
C    Sara         IT  44.000000          3000.0    Matrouh        3300.0   Low
D  Fatima      Sales  42.900000          4000.0       Suez        4400.0   Low
E  Hassan         IT  46.200000          5000.0      Banha        5500.0   Low
F   Amera      Sales  38.500000          6000.0       Giza        6600.0   Low
1     NaN        NaN        NaN             NaN    Unknown           NaN   Low
4     NaN        NaN  37.766667             NaN        NaN           NaN   Low

In [142]:
top_3_earners = df.sort_values(by="Monthly_Salary", ascending=False).head(3)
print(top_3_earners)

     Name Department   Age  Monthly_Salary   City  Salary_Bonus Level
F   Amera      Sales  38.5          6000.0   Giza        6600.0   Low
E  Hassan         IT  46.2          5000.0  Banha        5500.0   Low
D  Fatima      Sales  42.9          4000.0   Suez        4400.0   Low