In [2]:
import pandas as pd

<span style="font-size:45px;">series and Indexing</span>

In [ ]:
se= pd.Series([1,2,3,4], index=["A","M","S","T"])

In [ ]:
print(se)

In [ ]:
se.sum()

In [ ]:
se.mean()

In [ ]:
se.median()

In [ ]:
se.std().item()

In [ ]:
se["A"]=9

In [ ]:
se

<span style="font-size:45px;">Slicing</span>

In [ ]:
se["A":"S"]

In [ ]:
Values= [20,30,40,50]
Subjects= ["Math","English","Science","History"]

In [ ]:
pd.Series(Values, index=Subjects)

<span style="font-size:45px;">DataFrame</span>

In [ ]:
pd.DataFrame({'name': ["Ahmed", "Sara", "Samy"], 'age': [20, 33, 40]}, index=['A', 'B', 'C'])

In [ ]:
dict1={"Name":["Ali", "Ahmed", "Sara"], "Age":[20, 30, 40], "City":["Cairo", "Alex", "Giza"]}

In [ ]:
df=pd.DataFrame(dict1, index=['A', 'B', 'C'])

In [ ]:
df

In [ ]:
df["Age"].sum().item()

In [ ]:
df[["Name", "Age"]]

In [ ]:
df[df["Age"]>30]

In [ ]:
df["Age"] =[21,32, 34]

In [ ]:
df

<span style="font-size:45px;">Basic DataFrame Functions</span>

In [ ]:
df.info()

In [ ]:
df.describe()

<span style="font-size:45px;">Location</span>

In [ ]:
dictA={"Name":["Ali", "Ahmed", "Sara", "Fatima", "Hassan"], 
       "Age":[20, 30, 40, 50, 60], 
       "Salary":[1000, 2000, 3000, 4000, 5000]}

df = pd.DataFrame(dictA, index=['A', 'B', 'C', 'D', 'E'])

In [ ]:
df

In [ ]:
slice= df.loc["A":"C", ["Name", "Age"]]

In [ ]:
slice

In [ ]:
slice=df.iloc[0,[0,2]]

In [ ]:
slice

<span style="font-size:45px;">Modifying DataFrames</span>

In [ ]:
df["Weight"]=[60, 70, 80, 90, 100]

In [ ]:
df

In [ ]:
df.iloc[0,0]="Sameh"

In [ ]:
df

<span style="font-size:45px;">Handling missing data</span>

In [ ]:
dictA={#"Name":["Ali", "Ahmed", "Sara", "Fatima", "Hassan", None], 
       "Age":[20, None, 30, 40, 50, 60], 
       "Salary":[1000, 2000, 3000, 4000, None, 5000]}

df = pd.DataFrame(dictA, index=['A', 'B', 'C', 'D', 'E', 'F'])

In [ ]:
df

In [ ]:
df.isnull().sum()

In [ ]:
df.info()

In [ ]:
newdf=df.dropna()

In [ ]:
newdf

In [ ]:
df.fillna(df.mean())

In [ ]:
df.mean()

<span style="font-size:45px;">Grouping and Aggregation</span>

In [ ]:
dictb={"Name":["Ali", "Ahmed", "Sara", "Fatima", "Hassan"], 
       "Department":["IT", "HR", "IT", "HR", "IT"],
       "Salary":[1000, 2000, 3000, 4000, 5000]}

In [ ]:
df= pd.DataFrame(dictb)

In [ ]:
df

In [ ]:
mins_salary=df.groupby("Department")["Salary"].min()

In [ ]:
mins_salary

In [ ]:
sum_salary=df.groupby("Department")["Salary"].sum()

In [ ]:
sum_salary

<span style="font-size:45px;">Apply Function</span>

In [ ]:
def inc10(x):
    return x *1.10

In [ ]:
df

In [ ]:

df["Salary"].apply(inc10)

In [ ]:
df["New_salary"]=df["Salary"].apply(inc10)

In [ ]:
df

<span style="font-size:45px;">Reading Files</span>

In [ ]:
pd.read_csv(r'Path\to\file.csv')
# r is used instead of // to avoid problems with slashes in the path

In [ ]:
data=pd.read_csv(r'C:\Users\Bassel\Downloads\data_1.csv')

In [ ]:
data.head(3)

In [ ]:
data.info()

In [ ]:
data.isna().sum()

In [ ]:
data.fillna(data.mean(), inplace=True)

In [ ]:
data.isnull().sum()

In [ ]:
data.describe()

<span style="font-size:45px;">Filtering</span>

In [ ]:
data[data["Salary"]>100]

`<span style="font-size:45px;">Sort values</span>

In [ ]:
data.sort_values(by="Age", ascending=False)

<span style="font-size:45px;">Saving Data</span>

In [ ]:
import openpyxl

In [ ]:
data.to_excel(r'C:\Users\Bassel\Downloads\data.xlsx')

<span style="font-size:45px;">Merging and Joining</span>

In [ ]:
Dict1={"ID":[1,2,3,4],
       "Name":["Ali","Sara","Ahmed","Samy"],
       "Age":[20,25,30,35],
       "Salary":[1000,2000,3000,4000]}
df1=pd.DataFrame(Dict1)


Dict2={"ID":[1,2,3,1],
       "Department":["HR","PR","IT","HR"],
       }
df2=pd.DataFrame(Dict2)

In [5]:
df1

   ID   Name  Age  Salary
0   1    Ali   20    1000
1   2   Sara   25    2000
2   3  Ahmed   30    3000
3   4   Samy   35    4000

In [6]:
df2

   ID Department
0   1         HR
1   2         PR
2   3         IT
3   1         HR

In [9]:
result= pd.merge(df1,df2,on="ID")
result

   ID   Name  Age  Salary Department
0   1    Ali   20    1000         HR
1   1    Ali   20    1000         HR
2   2   Sara   25    2000         PR
3   3  Ahmed   30    3000         IT

In [10]:
result= pd.merge(df1,df2,on="ID", how="inner")
result

   ID   Name  Age  Salary Department
0   1    Ali   20    1000         HR
1   1    Ali   20    1000         HR
2   2   Sara   25    2000         PR
3   3  Ahmed   30    3000         IT

In [11]:
result= pd.merge(df1,df2,on="ID", how="right")
result

   ID   Name  Age  Salary Department
0   1    Ali   20    1000         HR
1   2   Sara   25    2000         PR
2   3  Ahmed   30    3000         IT
3   1    Ali   20    1000         HR

In [12]:
result= pd.merge(df1,df2,on="ID", how="left")
result

   ID   Name  Age  Salary Department
0   1    Ali   20    1000         HR
1   1    Ali   20    1000         HR
2   2   Sara   25    2000         PR
3   3  Ahmed   30    3000         IT
4   4   Samy   35    4000        NaN

<span style="font-size:45px;">Concatenation</span>

In [13]:
con= pd.concat([df1,df2])
con

   ID   Name   Age  Salary Department
0   1    Ali  20.0  1000.0        NaN
1   2   Sara  25.0  2000.0        NaN
2   3  Ahmed  30.0  3000.0        NaN
3   4   Samy  35.0  4000.0        NaN
0   1    NaN   NaN     NaN         HR
1   2    NaN   NaN     NaN         PR
2   3    NaN   NaN     NaN         IT
3   1    NaN   NaN     NaN         HR

In [14]:
con= pd.concat([df1,df2], join='inner')
con

   ID
0   1
1   2
2   3
3   4
0   1
1   2
2   3
3   1

In [15]:
con= pd.concat([df1,df2], join='inner', ignore_index=True)
con

   ID
0   1
1   2
2   3
3   4
4   1
5   2
6   3
7   1