In [ ]:
import pandas as pd

<span style="font-size:45px;">series and Indexing</span>

In [ ]:
se= pd.Series([1,2,3,4], index=["A","M","S","T"])

In [ ]:
print(se)

In [ ]:
se.sum()

In [ ]:
se.mean()

In [ ]:
se.median()

In [ ]:
se.std().item()

In [ ]:
se["A"]=9

In [ ]:
se

<span style="font-size:45px;">Slicing</span>

In [ ]:
se["A":"S"]

In [ ]:
Values= [20,30,40,50]
Subjects= ["Math","English","Science","History"]

In [ ]:
pd.Series(Values, index=Subjects)

<span style="font-size:45px;">DataFrame</span>

In [ ]:
pd.DataFrame({'name': ["Ahmed", "Sara", "Samy"], 'age': [20, 33, 40]}, index=['A', 'B', 'C'])

In [ ]:
dict1={"Name":["Ali", "Ahmed", "Sara"], "Age":[20, 30, 40], "City":["Cairo", "Alex", "Giza"]}

In [ ]:
df=pd.DataFrame(dict1, index=['A', 'B', 'C'])

In [ ]:
df

In [ ]:
df["Age"].sum().item()

In [ ]:
df[["Name", "Age"]]

In [ ]:
df[df["Age"]>30]

In [ ]:
df["Age"] =[21,32, 34]

In [ ]:
df

<span style="font-size:45px;">Basic DataFrame Functions</span>

In [ ]:
df.info()

In [ ]:
df.describe()

<span style="font-size:45px;">Location</span>

In [81]:
dictA={"Name":["Ali", "Ahmed", "Sara", "Fatima", "Hassan"], 
       "Age":[20, 30, 40, 50, 60], 
       "Salary":[1000, 2000, 3000, 4000, 5000]}

df = pd.DataFrame(dictA, index=['A', 'B', 'C', 'D', 'E'])

In [82]:
df

     Name  Age  Salary
A     Ali   20    1000
B   Ahmed   30    2000
C    Sara   40    3000
D  Fatima   50    4000
E  Hassan   60    5000

In [ ]:
slice= df.loc["A":"C", ["Name", "Age"]]

In [ ]:
slice

In [ ]:
slice=df.iloc[0,[0,2]]

In [ ]:
slice

<span style="font-size:45px;">Modifying DataFrames</span>

In [74]:
df["Weight"]=[60, 70, 80, 90, 100]

In [75]:
df

     Name  Age  Salary  Weight
A     Ali   20    1000      60
B   Ahmed   30    2000      70
C    Sara   40    3000      80
D  Fatima   50    4000      90
E  Hassan   60    5000     100

In [76]:
df.iloc[0,0]="Sameh"

In [77]:
df

     Name  Age  Salary  Weight
A   Sameh   20    1000      60
B   Ahmed   30    2000      70
C    Sara   40    3000      80
D  Fatima   50    4000      90
E  Hassan   60    5000     100

<span style="font-size:45px;">Handling missing data</span>

In [107]:
dictA={#"Name":["Ali", "Ahmed", "Sara", "Fatima", "Hassan", None], 
       "Age":[20, None, 30, 40, 50, 60], 
       "Salary":[1000, 2000, 3000, 4000, None, 5000]}

df = pd.DataFrame(dictA, index=['A', 'B', 'C', 'D', 'E', 'F'])

In [108]:
df

    Age  Salary
A  20.0  1000.0
B   NaN  2000.0
C  30.0  3000.0
D  40.0  4000.0
E  50.0     NaN
F  60.0  5000.0

In [109]:
df.isnull().sum()

Age       1
Salary    1
dtype: int64

In [110]:
df.info()

<class 'pandas.DataFrame'>
Index: 6 entries, A to F
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     5 non-null      float64
 1   Salary  5 non-null      float64
dtypes: float64(2)
memory usage: 144.0+ bytes

In [111]:
newdf=df.dropna()

In [ ]:
newdf

    Age  Salary
A  20.0  1000.0
C  30.0  3000.0
D  40.0  4000.0
F  60.0  5000.0

In [117]:
df.fillna(df.mean())

    Age  Salary
A  20.0  1000.0
B  40.0  2000.0
C  30.0  3000.0
D  40.0  4000.0
E  50.0  3000.0
F  60.0  5000.0

In [116]:
df.mean()

Age         40.0
Salary    3000.0
dtype: float64

<span style="font-size:45px;">Grouping and Aggregation</span>

In [152]:
dictb={"Name":["Ali", "Ahmed", "Sara", "Fatima", "Hassan"], 
       "Department":["IT", "HR", "IT", "HR", "IT"],
       "Salary":[1000, 2000, 3000, 4000, 5000]}

In [130]:
df= pd.DataFrame(dictb)

In [131]:
df

     Name Department  Salary
0     Ali         IT    1000
1   Ahmed         HR    2000
2    Sara         IT    3000
3  Fatima         HR    4000
4  Hassan         IT    5000

In [133]:
mins_salary=df.groupby("Department")["Salary"].min()

In [134]:
mins_salary

Department
HR    2000
IT    1000
Name: Salary, dtype: int64

In [135]:
sum_salary=df.groupby("Department")["Salary"].sum()

In [136]:
sum_salary

Department
HR    6000
IT    9000
Name: Salary, dtype: int64

<span style="font-size:45px;">Apply Function</span>

In [140]:
def inc10(x):
    return x *1.10

In [139]:
df

     Name Department  Salary
0     Ali         IT    1000
1   Ahmed         HR    2000
2    Sara         IT    3000
3  Fatima         HR    4000
4  Hassan         IT    5000

In [145]:

df["Salary"].apply(inc10)

0    1100.0
1    2200.0
2    3300.0
3    4400.0
4    5500.0
Name: Salary, dtype: float64

In [148]:
df["New_salary"]=df["Salary"].apply(inc10)

In [149]:
df

     Name Department  Salary  New_salary
0     Ali         IT    1000      1100.0
1   Ahmed         HR    2000      2200.0
2    Sara         IT    3000      3300.0
3  Fatima         HR    4000      4400.0
4  Hassan         IT    5000      5500.0

<span style="font-size:45px;">Reading Files</span>

In [ ]:
pd.read_csv(r'Path\to\file.csv')
# r is used instead of // to avoid problems with slashes in the path

In [156]:
data=pd.read_csv(r'C:\Users\Bassel\Downloads\data_1.csv')

In [158]:
data.head(3)

   Salary  Gender   Age  PhD
0   140.0     1.0  47.0  1.0
1    30.0     0.0  65.0  1.0
2    35.1     0.0  56.0  0.0

In [159]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Salary  97 non-null     float64
 1   Gender  98 non-null     float64
 2   Age     97 non-null     float64
 3   PhD     98 non-null     float64
dtypes: float64(4)
memory usage: 3.3 KB

In [160]:
data.isna().sum()

Salary    3
Gender    2
Age       3
PhD       2
dtype: int64

In [163]:
data.fillna(data.mean(), inplace=True)

       Salary  Gender   Age  PhD
0   140.00000     1.0  47.0  1.0
1    30.00000     0.0  65.0  1.0
2    35.10000     0.0  56.0  0.0
3    30.00000     1.0  23.0  0.0
4    80.00000     0.0  53.0  1.0
..        ...     ...   ...  ...
95   18.60000     1.0  26.0  0.0
96  152.00000     1.0  56.0  1.0
97    1.80000     1.0  28.0  0.0
98   53.52732     0.0  44.0  0.0
99    4.00000     0.0  24.0  0.0

[100 rows x 4 columns]

In [164]:
data.isnull().sum()

Salary    0
Gender    0
Age       0
PhD       0
dtype: int64

In [165]:
data.describe()

           Salary      Gender         Age         PhD
count  100.000000  100.000000  100.000000  100.000000
mean    53.527320    0.510204   47.422680    0.387755
std     41.767425    0.497365   14.946257    0.484771
min      0.250000    0.000000   20.000000    0.000000
25%     21.500000    0.000000   32.000000    0.000000
50%     40.850000    0.755102   49.000000    0.000000
75%     75.500000    1.000000   60.000000    1.000000
max    190.000000    1.000000   77.000000    1.000000

<span style="font-size:45px;">Filtering</span>

In [172]:
data[data["Salary"]>100]

    Salary  Gender   Age  PhD
0    140.0     1.0  47.0  1.0
8    125.0     1.0  44.0  1.0
12   150.0     1.0  60.0  1.0
14   130.0     1.0  65.0  0.0
16   130.0     1.0  65.0  0.0
18   190.0     1.0  66.0  1.0
42   106.0     1.0  77.0  1.0
56   160.0     1.0  61.0  1.0
60   102.0     1.0  66.0  1.0
73   152.0     1.0  71.0  1.0
77   120.0     1.0  58.0  1.0
93   115.0     0.0  54.0  0.0
96   152.0     1.0  56.0  1.0

`<span style="font-size:45px;">Sort values</span>

In [173]:
data.sort_values(by="Age", ascending=False)

       Salary  Gender   Age       PhD
42  106.00000     1.0  77.0  1.000000
73  152.00000     1.0  71.0  1.000000
90   89.00000     1.0  71.0  1.000000
83    9.00000     1.0  71.0  0.000000
76   30.00000     1.0  69.0  0.387755
..        ...     ...   ...       ...
3    30.00000     1.0  23.0  0.000000
10   53.52732     1.0  22.0  0.000000
37    9.00000     0.0  22.0  0.000000
53   34.80000     0.0  22.0  0.000000
74   39.80000     0.0  20.0  0.000000

[100 rows x 4 columns]

<span style="font-size:45px;">Saving Data</span>

In [178]:
import openpyxl

In [181]:
data.to_excel(r'C:\Users\Bassel\Downloads\data.xlsx')

<span style="font-size:45px;">Merging and Joining</span>