In [3]:
import pandas as pd

<span style="font-size:45px;">series and Indexing</span>

In [10]:
se= pd.Series([1,2,3,4], index=["A","M","S","T"])

In [11]:
print(se)

A    1
M    2
S    3
T    4
dtype: int64

In [12]:
se.sum()

np.int64(10)

In [13]:
se.mean()

np.float64(2.5)

In [14]:
se.median()

np.float64(2.5)

In [16]:
se.std().item()

1.2909944487358056

In [18]:
se["A"]=9

In [19]:
se

A    9
M    2
S    3
T    4
dtype: int64

<span style="font-size:45px;">Slicing</span>

In [24]:
se["A":"S"]

A    9
M    2
S    3
dtype: int64

In [26]:
Values= [20,30,40,50]
Subjects= ["Math","English","Science","History"]

In [27]:
pd.Series(Values, index=Subjects)

Math       20
English    30
Science    40
History    50
dtype: int64

<span style="font-size:45px;">DataFrame</span>

In [29]:
pd.DataFrame({'name': ["Ahmed", "Sara", "Samy"], 'age': [20, 33, 40]}, index=['A', 'B', 'C'])

    name  age
A  Ahmed   20
B   Sara   33
C   Samy   40

In [30]:
dict1={"Name":["Ali", "Ahmed", "Sara"], "Age":[20, 30, 40], "City":["Cairo", "Alex", "Giza"]}

In [35]:
df=pd.DataFrame(dict1, index=['A', 'B', 'C'])

In [36]:
df

    Name  Age   City
A    Ali   20  Cairo
B  Ahmed   30   Alex
C   Sara   40   Giza

In [41]:
df["Age"].sum().item()

90

In [42]:
df[["Name", "Age"]]

    Name  Age
A    Ali   20
B  Ahmed   30
C   Sara   40

In [45]:
df[df["Age"]>30]

   Name  Age  City
C  Sara   40  Giza

In [46]:
df["Age"] =[21,32, 34]

In [47]:
df

    Name  Age   City
A    Ali   21  Cairo
B  Ahmed   32   Alex
C   Sara   34   Giza

<span style="font-size:45px;">Basic DataFrame Functions</span>

In [48]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, A to C
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   City    3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0+ bytes

In [49]:
df.describe()

        Age
count   3.0
mean   29.0
std     7.0
min    21.0
25%    26.5
50%    32.0
75%    33.0
max    34.0